[[Expat]]
arch = "aarch64"
git-tree-sha1 = "58a823f5db16dad200bcc0c57b93a4442e672c70"
os = "macos"

    [[Expat.download]]
    sha256 = "4f10912928fb1be59d263d731d856bad0a32e3c95c9eee448e2136714625ceed"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.aarch64-apple-darwin.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "a4782d2debbd92fafef09289a781fbeccc5a568b"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "191dc09f2746ee0646b0ec9e8e8ed83ce2a5fe68aa8df096258aa6e0a0d70712"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.aarch64-linux-gnu.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "f57b8222ee18588e9c8d818419ba95c854b0a2ba"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "9007115ea99abcbac889f43f996982d5edb41dc44dadbdb64280000e899db2c6"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.aarch64-linux-musl.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "bac58c329a2295e46dd287189bb6e01c02a99cf1"
os = "freebsd"

    [[Expat.download]]
    sha256 = "b3f1da902fa4e90bf43b142f21d0130883c3067268ef49d26bb14c94fadfc408"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.aarch64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e22d78a0f06815c8ace792866a2db00a552e76a"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "c2bce42d234e40deb79707028c6bf1faaad108b5327f426fa4b8f297dbfc9dfd"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.armv6l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c0ca7f8f2df737939903362beb2e09691714ea27"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "d1bc4a63f75c43aaf5ff4b85a9beec29b7604f29c18db49edc129d5fbee88072"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.armv6l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3d55ccc9aa7f5bf0cca2e9ee59dcbdcbbcbaa4bb"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "d757f438c59bbb5c1c49346cb44986e72b9f6c2a1327aae137542271e94ad0ac"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.armv7l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "02a9962c28de65f797e28a5ada2e420df8b7e78f"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "5f57909f0ecb01a2f859f51a0c44785b58b8f9fe4cbca9c89b5ac9539abdefd7"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.armv7l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "054761f74d25214fd3396172c8ec80c0da4ef529"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "ee609257653ecad874b02981cb852eb6c4b0c88ca19b92cb938526fbe33f613f"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.i686-linux-gnu.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "57f605812e94d6b03850103fcb41dc52326ad465"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "bcbb5fa31d654ce44807f8a9d69bee1422ca29aec48a53baea391bdef6c583c6"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.i686-linux-musl.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "f33fa733e400deebbeeec69645a4da9204b5c519"
os = "windows"

    [[Expat.download]]
    sha256 = "3cf020e8a632512bc49c8f4833706914cd7693c9cc078c4a9609835be1fab910"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.i686-w64-mingw32.tar.gz"
[[Expat]]
arch = "powerpc64le"
git-tree-sha1 = "022f04b9f16af4dde9e06d5f95572174eddfd913"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "1eb4d8b02bb9cdbfe77b825d27168971aa0a97c9985a11e07dca2916e93cd603"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.powerpc64le-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "aee11b0a78c2f26d95b8485c0decc2994dc8b3f7"
os = "macos"

    [[Expat.download]]
    sha256 = "04768ac9fe598a5be2a3a929711b4affe8376b5bd510820b159067d6ba2518f8"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.x86_64-apple-darwin.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "a6a349d128402e13b9bba1cae5584db99e43048f"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "b350ac76836df1f9939fe685ebcaccf42cfa8347fb4b6705e5e1a9300cec9da4"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.x86_64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "f823774fb4f2b75ababfea41e3194775664ee860"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "c11a2547e50f80919550692c6f1387872e579e348841283676a51272b14ef21e"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.x86_64-linux-musl.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "3c9c137b049ac46f626dc8491ae2816ace792085"
os = "freebsd"

    [[Expat.download]]
    sha256 = "5dfe6adaecacba0c4a4e8b51722ae4d297aa3ec034ab386b8435c71c422d13d4"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.x86_64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "912698011dc48f8d210ecc9c6c61146bdc81790f"
os = "windows"

    [[Expat.download]]
    sha256 = "ac74f3f902eea829f5351a7bbdc994e1c712fd364787856776292167271e6ddc"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+1/Expat.v2.2.10.x86_64-w64-mingw32.tar.gz"
