[[Expat]]
arch = "aarch64"
git-tree-sha1 = "db252f8229adbf8934419d15ea3923592649be7a"
os = "macos"

    [[Expat.download]]
    sha256 = "9ff4f966abe3ac9cfc680f75cc2d3e8579216992e47be5ea6e0c6be1aae48d55"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.aarch64-apple-darwin.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "f8d9bccfcc66414520daadfaa8b67b15e85d9987"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "d2902cbc0988288bcaf0e79890946f4ab382b6092405373c98aefab020c4ed58"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.aarch64-linux-gnu.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "8ebfb21c043a831efa4ae9669e806bc0f5e1cc32"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "278acd0e18b5bb7aeff85e1ddab61d12ca96e5ae1ed269eb38a7ac69cc9547f6"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.aarch64-linux-musl.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "3193cc61e777c7a80346608c7978996d7481ca0f"
os = "freebsd"

    [[Expat.download]]
    sha256 = "7778ecdc97c76d94370934cb10a81ffb509d738aafba2cebf105a724a5160d09"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.aarch64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "95fc167c6598cb621375e314bb6bc6fec56c58e4"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "746e94fff1007d3c2dd3839847987e6613a77a49b5cf376d280cf0fc47294b3a"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.armv6l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "47acc38d25215ad9d402bba2896de5944420a59c"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "2752c3e4e6688c762221749db96df7c8dea762fe2d406de3891115038d222f14"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.armv6l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8c71d08a5fc1895d33aef3fd39a231f2c5f8033e"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "d26d18cc78324b8bf94afaff863c856ebbcf7c86b4e43e23828b47d0d3513595"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.armv7l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6ce1f9fdcbfa84f89e9d936a847d7c57bda737bb"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "7c3d8028b37e037d4c2022fe3fa897ffb271877f26a3f7b6c281b2bd893e4b9e"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.armv7l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "4a84e251e82ac6efb6b2ccbe7ed4ead0dc3366b9"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "5ff1df98bdfdf69f43af40cb66ae6fa16b02ed4ed872468f937aa2b83c6fbf72"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.i686-linux-gnu.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "c638f463802d10aa4b04c905be4766942b33fc12"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "90b950b7fc59f0a93ca8d0bb01206e37446d4597a7e2c28ff6eb047d7954fca5"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.i686-linux-musl.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "d11100c0a682fc738684276f28c9ebee4eac6cfb"
os = "windows"

    [[Expat.download]]
    sha256 = "4281719614380b3a44a2f04f58cf21ef03c0f66890ed4ec2dac80a7a4025a4f4"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.i686-w64-mingw32.tar.gz"
[[Expat]]
arch = "powerpc64le"
git-tree-sha1 = "9a2ac246dfee8b3caa5ece5b932074f2172c44a1"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "cdbc4c95b4a4e46291dc745ac056918b6df67fda5dd27f8cc19a837d4c11a5f7"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.powerpc64le-linux-gnu.tar.gz"
[[Expat]]
arch = "riscv64"
git-tree-sha1 = "60c347588ce8ba2c93e5bf6d2c648a6e9b6f335b"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "2933775c5f217cd1470183312d508a28244abc3a0dc533a03661023ad2da39b2"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.riscv64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "2324d69973d6c1f443021a857421557b5518d944"
os = "macos"

    [[Expat.download]]
    sha256 = "711f38dd263687cf8747adf8b2ae99e5fe494e2ed6b850e5b3710d8db441e195"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.x86_64-apple-darwin.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "bc453da02b4f3eb66080b1c3ea9403e2c817f042"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "6d76bb2d9927d81fef14640841ad8e631aacd04343da4bc8a29385a738ae3bee"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.x86_64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "9845fb693c0bdf463e9aa66d3a709ca9465cb232"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "b8d37368ffbfc9f20cc7e6bdac48382e0a5ae74c5499d46d32769898e0eddb9f"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.x86_64-linux-musl.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "a764c804bdcc4e2d454b972688bf8b3b8f527ab0"
os = "freebsd"

    [[Expat.download]]
    sha256 = "4160693f9c558ad12354e86361a7698b4db4452f8a11cd8516ad3fdd9070897c"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.x86_64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "27d45364c9d88da2e94c97be42d53ef71549c1fb"
os = "windows"

    [[Expat.download]]
    sha256 = "69eff800d853d4c8b8ae405f8e5b3fcb0543588ee2671161b605376f9434cb96"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.3+0/Expat.v2.8.3.x86_64-w64-mingw32.tar.gz"
