[[Expat]]
arch = "aarch64"
git-tree-sha1 = "093d6407945e0c42a70ddb9d4336920afc0047a3"
os = "macos"

    [[Expat.download]]
    sha256 = "a09e8da8915e72d7453eba3cc4dee84b5cf323906fcb046a699e2319cc06149f"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.aarch64-apple-darwin.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "773cd9563110c368a794cb73e516bc67500f8804"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "ecb25ead7de4cca0e96e21c85e3e50f7b85a7126e5f8e879d961395219ee4563"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.aarch64-linux-gnu.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "d842c5206b6d9272d5df3d32824be43124ed15ea"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "ea8e0f2850f1c048a2004770c9bdacbe5fa0a3f1a3a90cbc4e8c63544b124b83"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.aarch64-linux-musl.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "a1eb6f63e3697497bfce322a2185054d5f21b7d2"
os = "freebsd"

    [[Expat.download]]
    sha256 = "027af7eb99d61c19dd56606e83ab0d188258e58d80e4a48e65a8fbad8efab26e"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.aarch64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "89c922c5374c0d976804a6858714e318a9e64612"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "1e015fac5a3c622b5d0873452e6d18f39b33cb335de7e4e9719b2d724cb5582c"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.armv6l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ad5e792d45623b8a901c4df229449104c00ed73"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "786c17f073315b5c84c20218f286e20d408d2a066cfb5e43335077b10bc3119a"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.armv6l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "773e79ddc7d77ec42c93cf446308501c0e604fb6"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "e23e51d4929d3dba8474b4bf7edd9384904adcd47d489c176fcb3001b017395b"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.armv7l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8a35e93d0cbfb1bbdb0f12d186a02a8848a5246"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "f99053d3b77588a5dc7da5d10821329eef96a13cecb8e4802d4ce17ca055dd83"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.armv7l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "361c4126e6ac8f91f6e24815d12f04594b8053cd"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "a8f4a60137bdb96cc027fb6b30bf55f88bbebe3fd81fd652f21b3f04d3710b38"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.i686-linux-gnu.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "b5d5da1d74c5239f27337a60fe2f3b9dc5282937"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "858c55f36626bf0589ff70aef9bad0b656970557255df81264dd2fe114645d00"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.i686-linux-musl.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "77956de781b3ee8bf03697617a8e8114c63e3b79"
os = "windows"

    [[Expat.download]]
    sha256 = "2783be257eb4a2c5ffac93dd668285ba84d3945332a51556e14a7cdada6e58e6"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.i686-w64-mingw32.tar.gz"
[[Expat]]
arch = "powerpc64le"
git-tree-sha1 = "6b8c471069901416dbf535ade710a63feefdca71"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "a976bf16198112250cdec46471a76ba828502753f966dae817ad2247cc8be983"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.powerpc64le-linux-gnu.tar.gz"
[[Expat]]
arch = "riscv64"
git-tree-sha1 = "6bfa5c39b8b99246839c4026836d7ee99d170a9e"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "9436f6d8c5a41a18dfeaa62636d0c7ebe3c290daa99e95ce1c991689dbf813ce"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.riscv64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "c101c920c7f5db72fa3bd115f4f680067756e090"
os = "macos"

    [[Expat.download]]
    sha256 = "9473c3b80865fadd777b38d59fd0b28eb2c9a4f7811307afed78dde52be65f5b"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.x86_64-apple-darwin.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "cc3c4d36f2cf650d73959f9d7dec5cd0630bfb01"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "347ad7c48fd5b37b81fd50e1cb6cf4b6c8d537c303db5794c8b78630ca737b61"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.x86_64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "feb1543758a70372a9764c4b00a40c82f05493d1"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "37a59a3a1dc79c4990a4674c53fe3b20f843c8c833490e59babfd39d328b9f2f"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.x86_64-linux-musl.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "0f23ef6db49095a81569d3bf291594cd4a11aa53"
os = "freebsd"

    [[Expat.download]]
    sha256 = "d4fcedb38b6b471e51b26bf16dfc84daf396f68dfa47e7c9abc545a2ed5c0a94"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.x86_64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "51e4c0b5a201939ab2352553b85f5d0932d5cf03"
os = "windows"

    [[Expat.download]]
    sha256 = "f8c6034b3c1eb1d93bb76202db2a7c86830b8e496ea9e5cd42a979a979ad42b8"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.7.1+0/Expat.v2.7.1.x86_64-w64-mingw32.tar.gz"
