[[Expat]]
arch = "i686"
git-tree-sha1 = "d2b09d4dd0bbfbb8e2f3a8642071b4e60f58f378"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "f23162cfd124b6d8bb01e6263cfe5711156e0a7f623cb969021807acd1637865"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.i686-linux-musl.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "0b27ff626b324cee1ed3fa30e8bb55662a7e249c"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "b5cdd7fe335eb614cb48565ca79b3f38a5befa50e7c7d07b113be6f37bd7bd5a"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.aarch64-linux-musl.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "55fd3bb82eb7a6354fb96b57cd3e80597f57c36d"
os = "windows"

    [[Expat.download]]
    sha256 = "5798ae649af06812267b55dbfbb752408228cd23ea43f4d6ed32e3a30b2ef43a"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.i686-w64-mingw32.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "147467d224f19885990ec02195d5789f6a6144a4"
os = "windows"

    [[Expat.download]]
    sha256 = "917bc26c7c8c7949eb5561bdca4c834965244785f65f5470c9fe336648c362bc"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.x86_64-w64-mingw32.tar.gz"
[[Expat]]
arch = "armv7l"
git-tree-sha1 = "1f572a7f4c003db041efcc552a4e68fe0b3751a6"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "60b7cf7c2ff36fe304e6af056a810e1a798e652a60fe53e6542345194e86541c"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.armv7l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv7l"
git-tree-sha1 = "e9240e64315a7d4cc76cc908cf483cca85764a07"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "edd4f2f615d72ddefe815c21eafa1e03f76ac4ffa35294787e60602628098185"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.armv7l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "f8c61af0485a61c39efb72eaa28c5a4bf1378faa"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "e0c2c5080fe42f32ab2d9308335f2fa3c2b32b89197cef39fc8589fd357ca640"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.i686-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "58a0d0c25b6c326d9f6c2efc2f67813a72d53e8a"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "4f0615a31e50a48f7906c06b6e1778789562da77698f65211a8e3c087f7586db"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.x86_64-linux-gnu.tar.gz"
[[Expat]]
arch = "powerpc64le"
git-tree-sha1 = "03ede8db56500611e7326d066365cda3173f6078"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "3e2753964b4ea3fb37813d3c30ca61627e06b0994a1a2e5c11c05658019fee00"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.powerpc64le-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "3b8c8bccbdeab8a80f9ad933523e612cb8e40811"
os = "macos"

    [[Expat.download]]
    sha256 = "1af8114ec656c06f3d97ce54a84544c662ca67d8c2fdf3567e5dfc769cfd060a"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.x86_64-apple-darwin14.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "8900d80cff2700af924fa8b2e6c7a52491fd3a78"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "1a913a8e213d68ae4271426c0f2107683d947009d32c66913e72f27d61aaf07b"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.aarch64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "02811853e31655798f04bc28fec1c7336ce9e59b"
os = "freebsd"

    [[Expat.download]]
    sha256 = "50d1c743574d5aaf353d591915b2b120f503d2277f8b570f6964c8d8fe0fe813"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.x86_64-unknown-freebsd11.1.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "c92feb702d4a49a52bcae8f5c671c13e109c2f1e"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "6a5cee2149d132b5f337bb53ef8a978c96e35ba4b9d54baad981062d4105eb39"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+1/Expat.v2.2.7.x86_64-linux-musl.tar.gz"
