[[Expat]]
arch = "aarch64"
git-tree-sha1 = "a0c1e4c8f7d685fbfe4d49edae87e36b60ea60b2"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "20b47106ea44be73e37a70e92c7f63f2f9ee19c6d41c433e130010963ad5e7df"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.aarch64-linux-gnu.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "f1bbd005fb5b3488947a06b7d32987702390ebc0"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "a32ed28ecc1da6282964379944ac2663f4b40b0e78f28e3472cbcc0fef4f3d54"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.aarch64-linux-musl.tar.gz"
[[Expat]]
arch = "armv7l"
git-tree-sha1 = "436bb12929a6d071e12ef397b38b298a79003fc2"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "433a1df394c72de82847ef229e7c8f927427b25a79c0d506ff78f917e037132a"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.armv7l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv7l"
git-tree-sha1 = "07e8510a18441a63a1e052601192553ea87a1565"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "027d72c17c665eb5da2d8517ab1b833ee8511f9222104066f97f91ddd77c38a6"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.armv7l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "9f5f0856141cbaa4df122072b4d183b056bca054"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "e3b75cbd05cfea378b48807bdb9afd0018c82bca0009580ef975458a3bb87c51"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.i686-linux-gnu.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "db7145c9214c778a1f30a0dfa8ccab91e68294d9"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "1113f3d8ffa825c40b825d18f5f239eb9010d4bded56a11490291537e1539b12"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.i686-linux-musl.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "f25bcc580e32455d047d84ed3f41397bda705901"
os = "windows"

    [[Expat.download]]
    sha256 = "15f0ac2de99277c01a9f37065bfc0530e3128ea653fec2439daf8c50bce326f2"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.i686-w64-mingw32.tar.gz"
[[Expat]]
arch = "powerpc64le"
git-tree-sha1 = "237449ee1c5f0dcefe022f9214c124c8fdb1a8c2"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "db15785f0708071febd605a5bd15e5c760a785cee155b167755b455dcaaf9508"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.powerpc64le-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "5309ae1017b247935837d4a140cbbb984afb062b"
os = "macos"

    [[Expat.download]]
    sha256 = "ce0d0fbc9ec848d481eb9656ad99853f95f8020669cabf7a219d2667f367f6e5"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.x86_64-apple-darwin14.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "652e052d1992a1ad5b132e9da16cee8f3c022502"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "14b94a1e5cbd706f45bfd153c5b530abfbe196f8693640f304e58096ecd2e3d7"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.x86_64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "dfb20366b10e27e185de09c360ca98f92e8c3b09"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "9033bd53d45af578d7e9c3dc792765db69fd86f3296872bb110ae4a8fe8d6cfe"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.x86_64-linux-musl.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "8b1b5a95573a7a5c4b1170e06de402ee4dcf10dc"
os = "freebsd"

    [[Expat.download]]
    sha256 = "3acb525ff71ee143679c699b51059c8dd9ec1e567f6962cad60782820d133463"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.x86_64-unknown-freebsd11.1.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "7963f55ce3cbbf780a9e33907f714a832dee7e8b"
os = "windows"

    [[Expat.download]]
    sha256 = "578302b85ff5b4ac99abed5c267a27443e7c1ad71f1b72b07d532db4a996d409"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+3/Expat.v2.2.7.x86_64-w64-mingw32.tar.gz"
