[[Expat]]
arch = "aarch64"
git-tree-sha1 = "b53d3c68aa0812e5ae574464a3198d17d79ded1a"
os = "macos"

    [[Expat.download]]
    sha256 = "db15d362d8b2a1095864acd5339d78858e3abbc30c42af2aa4290eaa59e0cfcd"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.aarch64-apple-darwin.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "d35cae40a292f0c068a06ae6e5b61519ba942b75"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "0d55de405f2fdc4530979c6ca9fcb84d5bfd662076c957150613b2a9cada8322"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.aarch64-linux-gnu.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "0433704d77f1e9505aa7a715cd256ff2e8031c43"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "11d3453d6f0bf7bceef319a7991b61c65abe147f65d569029972d02b5f56ea26"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.aarch64-linux-musl.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d4dbf7e78d3b3eb909e902ba54331bfc493fc584"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "9c36619edef4117bd1e3f5d72b86fd1b0f182d49c1414dbc8a262393982afe9b"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.armv6l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7a94110ae8e520a3fc1d5774a8150f1af2bb2413"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "966d210eb5ba388a59712a0a55818662e6bf7a403277bf59d8e07457a6e38eae"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.armv6l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4c033099a3bc192d4f7af09fb7c88537789f0808"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "2806fe4e65b5dc3dadcb5041ff5f80560e5157994561ac360540f625c40e1367"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.armv7l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9bdacd87f419d2977e51a00e88fe125c6b98e554"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "b95f128f36157d4f12e875bb2855a2a318204e8532d63441e167657505a01e4f"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.armv7l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "d337862b844bc173523c7d3281d9f463d49f2b97"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "0e62340b77a5ed119de217fecad87e90344a8c85a0951997c83f24e9446a295f"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.i686-linux-gnu.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "73d3dbba9fdfd081612a22859e974d96b32b9635"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "4e5678eeee3cb39c7aca9ddd83eda9a78a4e93b630f71fe50f77b2afc68bda31"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.i686-linux-musl.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "8132e22dd32c28710021122df27deb46ea168604"
os = "windows"

    [[Expat.download]]
    sha256 = "ef53b0297c9de0bb7e798ae49411cfe6ec817d31182cf935743d2bde87c99d37"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.i686-w64-mingw32.tar.gz"
[[Expat]]
arch = "powerpc64le"
git-tree-sha1 = "ba26d33dd8281ad1d55abb543d420927601c7f15"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "6188aeec1e1bde5943b4036c6c4e222bacbf41428a67fa6c9186d09ad60a773b"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.powerpc64le-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "4ef31a32cc88f589244c86dd5d6ea49b901b1a41"
os = "macos"

    [[Expat.download]]
    sha256 = "7a2cbba47ab4f918014b6a7d2f3e9a1e84f74c7349a8d7e64adedf5986495acb"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.x86_64-apple-darwin.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "1308e48c3f4f2fd9adaa56b9bd4a86a995d50abd"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "925f8c5b93437ab6e3bf963be802ba71e24f95ecc8ad450fa4793d794b8847d8"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.x86_64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "7065effbd664b19e03ba72b4181b5377f1519b4c"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "a0dd5f31a4f016238382ebc59b9bf1ca6f0feeea57f92b2bb6259b1a6015ae82"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.x86_64-linux-musl.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "f6cac9c7c81901bdea8226624199290c849eb8fd"
os = "freebsd"

    [[Expat.download]]
    sha256 = "0c2445fbf26b5633f10ee074a482181a240705925525214c676ee59e24b08ba3"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.x86_64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "4bacc938de39358bcb456ff732a37239e7e827f1"
os = "windows"

    [[Expat.download]]
    sha256 = "c9bc7109b1982431d5eafbf7b1913b0d5264f78387c31beb2b209887ffd1c8b6"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.2+0/Expat.v2.6.2.x86_64-w64-mingw32.tar.gz"
