[[Expat]]
arch = "aarch64"
git-tree-sha1 = "39f68ac8c59e5e6225ab6a49e54e85dddd98e2cc"
os = "macos"

    [[Expat.download]]
    sha256 = "2a73cbae9e29e60a381c4e37029ef8a30c1509a1d6031534dea08f77a0139aa8"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.aarch64-apple-darwin.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "8e15cc8681e87147d17fd1fb8c82ceeb7713f79a"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "1757532c8fb7219d1400939f8bcd0b01a0b9908bcf14e35b34ec022b1fc941ef"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.aarch64-linux-gnu.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "d5a170c4deac5994803812a8f33c88f635a6b828"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "f7fa9cc4e4d16d933a8c143ddb0ad5d4587f08b59352c31bc5b64eec82d6cfcd"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.aarch64-linux-musl.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "19affa1f2750d0fd0fbd1748ea788273078d1a8d"
os = "freebsd"

    [[Expat.download]]
    sha256 = "c59681605cca9f8e27abfcf50bfe7ef7488b8576744a61385dd526e7360a8e24"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.aarch64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fe81a816aa471bdeba4823994cf54db6f6cea8c9"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "aeee889f9e60b9a243db5e85f90193edaf456cb6e092c5193fae1f435a94c5bb"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.armv6l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ccb9331ff77e55f80ba9aa7d82fc312017f1f2bf"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "7d6d1f51f4e1b954047265dada458b8103041d2b71a65dd346a3b3c7542f4ec1"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.armv6l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2194db192b6d1159f72c5bf67f2359c7347c97b2"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "78bbc55322491f691826e0ffd40068397ce0d8b6828a90caa99809d30fe514ac"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.armv7l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "672c8b6ec2fc63b877058bbf218e77baaa985656"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "1630410c65fe5ea7e07df7651a42eb0af776d0f206c4f0d85d093d16cac9abf8"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.armv7l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "1f2d67472c4cda76be6f6ee65dcd504984a9ec6c"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "0a3c077bd37e63a035c98fcdad0083699446fd2e850baa792ffcdc1a2cde1c0e"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.i686-linux-gnu.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "f0009c72dd8eb7ff91bc6ca2453138a47afa512a"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "a8c4e36aad1070bb7f73e162276b706427d7142324ef2b2638a7df13d548eade"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.i686-linux-musl.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "1be60b4dde31dbdf187f5202f7d26478d1c0be0f"
os = "windows"

    [[Expat.download]]
    sha256 = "7fdc372a93744f095621c3c27d537b76e5e8a6fd380112839c83f3e850004e7f"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.i686-w64-mingw32.tar.gz"
[[Expat]]
arch = "powerpc64le"
git-tree-sha1 = "d0cfc399900e35303d9bcb4fc3a4e4b76f98c650"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "3abe8c0673302949b2c7e97d346095267755e7c54b52aa13d173cde1090187ca"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.powerpc64le-linux-gnu.tar.gz"
[[Expat]]
arch = "riscv64"
git-tree-sha1 = "fab29f4bbfce30e2d9694710fb9f199dd15020c3"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "b21f43737315fb3773a3ab7895ae88a91ddea7aa082cd7a8061cb33df570a493"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.riscv64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "6dd9270bd265ca58656820e3e18b8241c60399ae"
os = "macos"

    [[Expat.download]]
    sha256 = "643fa74a2b3840f31edc3bb8d87632d330e8ca37561ee83fb03c8913d5e69f9d"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.x86_64-apple-darwin.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "4b211894da5431bad5044e4237ea99ec8fc0794b"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "c603a4b90f39e75f2b7d000a46d1a84da84050cf37e8889a1c8fd823dba71416"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.x86_64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "3c47fd379026d48bc983c263a9a3ab2f23d88eb8"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "98f0220b22489d87a2e77c559c2c135189a4fe16fb88768d61d2024189bf8c9d"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.x86_64-linux-musl.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "099e7bed15f992f2ff883531333a4e119c40c74d"
os = "freebsd"

    [[Expat.download]]
    sha256 = "0e3f2bf8d94ae0635327d9b4236e822339225db8bf5c88f1c191c4bc5d362314"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.x86_64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "7ee42f64cb5cec08ebd6deb70b97c57932952d21"
os = "windows"

    [[Expat.download]]
    sha256 = "e55be9a06c6d6697b0c57e9533f190538a89dedf1dd4948f4f7d5a317e931695"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.1+0/Expat.v2.8.1.x86_64-w64-mingw32.tar.gz"
