[[Expat]]
arch = "aarch64"
git-tree-sha1 = "becfd6f89f1a272ace2375b067f1153515ca70b3"
os = "macos"

    [[Expat.download]]
    sha256 = "657a872c1cf076e8869d633ce0cdc9d5ac9f317ddb2a887d7501974d85f16de1"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.aarch64-apple-darwin.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "2f55a57f3f604f4c7fd4af200bf93942665050f1"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "4d95dcab86ee70f6541887a0fc47f87c86b033893e1ea3e09f8c4712e0625ebb"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.aarch64-linux-gnu.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "8bf2e5b7151977df71bee5fd9e1d4cb2a1abf5e2"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "1ca57fc84790fc19ef55b69c445210d19b769a58c0e52381559d71b0febd584e"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.aarch64-linux-musl.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "8277b8b428049f1242e6e6810786e2b69e92d44b"
os = "freebsd"

    [[Expat.download]]
    sha256 = "addd8a2622b378a15c803e3b7fcbccdb584783e1a8fa553733afd2f17f12d0d1"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.aarch64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "057913c5ecf8e415ac21648b98f7f6775425ec9f"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "5c586da67cd934c6bd3d8aff364f764fa96c06ac005d3c9f8dc45099d0d211b1"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.armv6l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b1451996d88af7ac826825e921bf80333ec96f54"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "1e78b342128c4367dd5cf23ba1ee35b26ac00fcb1eac8925872bd136f345d108"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.armv6l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dd6e9e41fcaabb9ce9842a234fc67a4adb6712a0"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "4e2127b8e181fa89444888864f7a8c5c49f1bd2aa2a07e7aa2a198a66248fab9"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.armv7l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "403ea85f11b20dc8ffa2fe71c1ea81dd770abcfa"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "8143739b207708531f92ed49d49f4d843faeca76c54a64014b2d9557aceb3e2d"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.armv7l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "c02aaf7d885dd6e2ffae8bc5e89ce982a94c56a2"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "28268fc4d9394bdda651ae6ba2420a9bade40e8c546a3608669e64510eb77669"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.i686-linux-gnu.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "2dcb811cc1d6a9ef9f4616180dd88a7e5bb42ea1"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "dbd2b9600ade889127135dfdfafda42d51205532b6d8a21440ec5d7a4c3b1e54"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.i686-linux-musl.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "2f4b6eb38b972226a0733059b50ab08b19785db7"
os = "windows"

    [[Expat.download]]
    sha256 = "e70fe3f5261a75e4b01b79d5249953d434174e837c7f074845aaa3f12bec8de4"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.i686-w64-mingw32.tar.gz"
[[Expat]]
arch = "powerpc64le"
git-tree-sha1 = "5adc7dd6fc6bf8363f3700d89ae91ab075a56fa6"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "b42d0c1be15567dab1827604fb23a0286ca9aae39f1cc760276ebfc7ecf1dd85"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.powerpc64le-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "cf0f09ce1e838823335bd604cb7e2d9338247058"
os = "macos"

    [[Expat.download]]
    sha256 = "c9a2827d008b639553145809835be90e81a19345b0c5e2ac46acdb19a93d9f8f"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.x86_64-apple-darwin.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "96bc7b9ddb319d1a051535c85184aa2bf42dbd8b"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "c67f9ad8345cc5aa301f4b96f8644d6f6a57e6b302a80109ac5e7cdf576255f3"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.x86_64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "957114eb5307ea0d1c250a1772fd8efec980d811"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "27e8e896a4805f70407a0fdcc84ae31d53b419f28d8c18a261874155aa13eb25"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.x86_64-linux-musl.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "e9a6afc75ae48ef228b2fa80c84c338abdf9dac0"
os = "freebsd"

    [[Expat.download]]
    sha256 = "291b0da7cbf0465373bfd9c1637c1b541da53e134c07df168f0d973afada1469"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.x86_64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "abe9a24d2f229d936a82fa861765024908b5566b"
os = "windows"

    [[Expat.download]]
    sha256 = "d8c33e0e9ac52c3c2737f32f2ab10b4bdc58090bbc92f1252d87603b2d0f59c6"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.6.4+1/Expat.v2.6.4.x86_64-w64-mingw32.tar.gz"
