[[Expat]]
arch = "aarch64"
git-tree-sha1 = "5400ba09ed6875495a72294dbc7da19f18cafa1d"
os = "macos"

    [[Expat.download]]
    sha256 = "fed3d6a278591e3cc50154f702f1e5c5dfce1857d795ddf92f576d5cc396d7e5"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.aarch64-apple-darwin.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "9502576971197f40689a7574e8e43a20d6d0f204"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "714bc94c99a647dec76f3a724925a8abc2fc3bace35f0130e6231a9c3d4c9e01"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.aarch64-linux-gnu.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "dbcca1e774e57120ba429c679e65b2ec64bb20da"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "fb32fc1588748f2bd5a5918414fd9d5d621c409b30882864f397f0067692f887"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.aarch64-linux-musl.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "5bd7d14e74be0c8bf97e3ac5b2567524521627b1"
os = "freebsd"

    [[Expat.download]]
    sha256 = "4f324429e1bf971fd7257f9f31ccc9a65f5d116360aacf577d3a55ed6da701d8"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.aarch64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "df3c2d63422e3e9c76281cdbc03dc1dea9c0904a"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "ab089ef41ebcb2a41364531c26fbe14d9b43e4583e9a6030cd984f662ba85482"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.armv6l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e3e1ea38654bb84c4e3fe3398c9875b55bfd87fd"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "b305d5b00a1b09bb6169186b07d9b8f4fa576ba848262fb25aa444f665205f57"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.armv6l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9c4e0481e9b3ab1bd2aa2f84a5a516f081a384b7"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "1b194ac62a3d1242c1f4a55763f60bb2a96763afb6f304b57c6c399b53885e72"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.armv7l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d007cd5ec0106a7b2eba4e37b497efb642057ee3"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "678153efdb060fa2cce078cd718f2cbe89979405f1775a3b311cbce6709f7dd1"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.armv7l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "b0d2206cd74c1a2b7ade4ea94566be7c936642fa"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "add46c0421a5f07fd8124b7f2abed46e83bad1e3294f738c6b9dbbe4d3bc0eec"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.i686-linux-gnu.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "9d66efe91fdf1cc062fe31c6a354960c4950973a"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "c898fcd5ef4ddcc688ebf408d09b114f25cfdfeb81aeb107de814195de3b67fc"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.i686-linux-musl.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "c7ede0de3071a021b3d6646a7469c67a883021a5"
os = "windows"

    [[Expat.download]]
    sha256 = "f140fef5b5ddad36ca3379bab6c0654675f233180e364f9aa2548793045dce69"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.i686-w64-mingw32.tar.gz"
[[Expat]]
arch = "powerpc64le"
git-tree-sha1 = "7aa0c44f492d431ab869e85a7ebb11426193c074"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "9505dc921e4e2774465527a001816bbaf2cc825b6163ed41b68fbf34db4b2bbf"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.powerpc64le-linux-gnu.tar.gz"
[[Expat]]
arch = "riscv64"
git-tree-sha1 = "68c4ddae87336b47b3f3265d6909e87d6ba7edb5"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "dde60f05a5026359b20e1e36ff8e320ca69524299edf655ffdd7c7197c354615"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.riscv64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "eb4a2984f48974fb4416e181651cd1b0f3d346b2"
os = "macos"

    [[Expat.download]]
    sha256 = "5e94cc03f71a48d5bbea104aeeb90365f515e454be8ba69f3a143a6c4b0acf38"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.x86_64-apple-darwin.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "6a9659f63dd080d81e6657796b832866550c13b2"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "36db9228b7e3dbc7e810aa99c2cf769b17b6349bf7ca5316eb5fe50dbe107de3"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.x86_64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "2f89499e956ed7a3dca0e0f5d15ca355f6f76f45"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "234c5b2ed1c220d7344c61ff9feaebce5bf330928b7e7b7c0aae4de927c0ef09"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.x86_64-linux-musl.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "ae11065a87444d0670d235ef787614c7c8513f1e"
os = "freebsd"

    [[Expat.download]]
    sha256 = "8a86028e2d61d59fc06c5874a4c23483b01376de3d21bd55dd40beb7a95f0e10"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.x86_64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "a728eed1ad38ac4376074efc1b72cf4e9a79c945"
os = "windows"

    [[Expat.download]]
    sha256 = "64f571e33643be887833aec49054d96637083da5297ba0377ba3ad283c687145"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.8.2+0/Expat.v2.8.2.x86_64-w64-mingw32.tar.gz"
